 LIST METHODS
 
names=["suhas","smiley","sabitha","sathwika"]
print(len(names))
print("suhas" in names)  [" BOLLEAN VAULE"]{"in"}
print(names)
names.append("chinnu")
print(names)
names.remove("sathwika")
print(names)
names.insert(2,"ammu")
print(names)
names.clear()
print(names)

{:} = to start  block of codes  *****


FOR LOOPS

words=["a,m,m,u"]
print(words)
name=["chinnu"]
for item in "chinnu":
    print(item)
	
